spring:
  datasource:
    url: jdbc:h2:mem:dio-santander
    username: user
    password:
  jpa:
#    show-sql: true  # VER NO LOG
#    open-in-view: false
    hibernate:
      ddl-auto: create # HIBERNATE CRIA AS TABELAS
#    properties:
#      hibernate:
#        format_sql: true  # DEIXAR O LOG MAIS LEGIVEL COM A FORMATAÇÃO SQL
  h2:
    console:
      enabled: true
      path: /h2-console # ACESSAR O H2 VIA BROWSER
      settings:
        trace: false
        web-allow-others: false